---

  - hosts: localhost
    connection: local
    become: true
    user: root
    gather_facts: yes
    vars:
      # Openvpn_as
      config_db: false
      mysql_user: --> set user <
      mysql_pass: --> set password <
      database_url: --> set url <
      # Common
      install_dev_tools: false
      update_hostname: true
      update_time_config: true
      hostname: --> set hostname
      timezone: Europe/London
      server_restart: false
      # Letsencrypt
      letsencrypt_webroot_path: /var/www/html
      letsencrypt_email: user@example.net
      letsencrypt_cert_domains:
        - www.example.net
        - example.net
      letsencrypt_renewal_command_args: '--renew-hook "systemctl restart nginx"'
    roles:
      - openvpn_as
      - common
      - letsencrypt